"""Error code constants organized by module."""

# --- Config ---
E_CONFIG_INVALID_TYPE = "E_CONFIG_INVALID_TYPE"
E_CONFIG_PROXY_INVALID = "E_CONFIG_PROXY_INVALID"
E_CONFIG_MISSING_LOCAL = "E_CONFIG_MISSING_LOCAL"
E_CONFIG_MISSING_REMOTE = "E_CONFIG_MISSING_REMOTE"
E_CONFIG_MISSING_ACCESS = "E_CONFIG_MISSING_ACCESS"

# --- Allocate (BrowserFlare.allocate) ---
E_ALLOC_TIMEOUT = "E_ALLOC_TIMEOUT"
E_ALLOC_NO_RESOURCE = "E_ALLOC_NO_RESOURCE"
E_ALLOC_FAILED = "E_ALLOC_FAILED"
E_ALLOC_LOCAL_NOT_SUPPORTED = "E_ALLOC_LOCAL_NOT_SUPPORTED"

# --- Connect (BrowserFlare.connect / Session) ---
E_CONNECT_SESSION_NOT_FOUND = "E_CONNECT_SESSION_NOT_FOUND"
E_CONNECT_AUTH_DENIED = "E_CONNECT_AUTH_DENIED"
E_CONNECT_CDP_FAILED = "E_CONNECT_CDP_FAILED"
E_CONNECT_TIMEOUT = "E_CONNECT_TIMEOUT"
E_CONNECT_FAILED = "E_CONNECT_FAILED"

# --- Session ---
E_SESSION_CLOSED = "E_SESSION_CLOSED"
E_SESSION_UPDATE_PROXY_FAILED = "E_SESSION_UPDATE_PROXY_FAILED"
E_SESSION_UPDATE_RESOLUTION_FAILED = "E_SESSION_UPDATE_RESOLUTION_FAILED"

# --- Display (GUI Input) ---
E_INPUT_INVALID_COORDS = "E_INPUT_INVALID_COORDS"
E_INPUT_KEY_NOT_SUPPORTED = "E_INPUT_KEY_NOT_SUPPORTED"
E_INPUT_SCREENSHOT_FAILED = "E_INPUT_SCREENSHOT_FAILED"
E_INPUT_FAILED = "E_INPUT_FAILED"

# --- Browser lifecycle ---
E_BROWSER_DEAD = "E_BROWSER_DEAD"
E_BROWSER_NOT_AVAILABLE = "E_BROWSER_NOT_AVAILABLE"
E_BROWSER_RECOVERY_FAILED = "E_BROWSER_RECOVERY_FAILED"

# --- Page / Pages ---
E_PAGE_CRASHED = "E_PAGE_CRASHED"
E_PAGE_NAVIGATE_TIMEOUT = "E_PAGE_NAVIGATE_TIMEOUT"
E_PAGE_NAVIGATE_FAILED = "E_PAGE_NAVIGATE_FAILED"
E_PAGE_NOT_FOUND = "E_PAGE_NOT_FOUND"
E_PAGE_CURRENT_NOT_FOUND = "E_PAGE_CURRENT_NOT_FOUND"
E_PAGE_ELEMENT_NOT_FOUND = "E_PAGE_ELEMENT_NOT_FOUND"
E_PAGE_ACTION_TIMEOUT = "E_PAGE_ACTION_TIMEOUT"
E_PAGE_ACTION_FAILED = "E_PAGE_ACTION_FAILED"
E_PAGE_CLOSED = "E_PAGE_CLOSED"

# --- Evaluate ---
E_EVAL_SCRIPT_ERROR = "E_EVAL_SCRIPT_ERROR"
E_EVAL_SERIALIZE_FAILED = "E_EVAL_SERIALIZE_FAILED"

# --- Cookie ---
E_COOKIE_GET_FAILED = "E_COOKIE_GET_FAILED"
E_COOKIE_SET_FAILED = "E_COOKIE_SET_FAILED"
E_COOKIE_CLEAR_FAILED = "E_COOKIE_CLEAR_FAILED"
E_COOKIE_STATE_SAVE_FAILED = "E_COOKIE_STATE_SAVE_FAILED"
E_COOKIE_STATE_LOAD_FAILED = "E_COOKIE_STATE_LOAD_FAILED"

# --- Network ---
E_NETWORK_ROUTE_FAILED = "E_NETWORK_ROUTE_FAILED"
E_NETWORK_ROUTE_REMOVE_FAILED = "E_NETWORK_ROUTE_REMOVE_FAILED"
E_NETWORK_HEADERS_FAILED = "E_NETWORK_HEADERS_FAILED"

# --- CAPTCHA ---
E_CAPTCHA_DETECTION_FAILED = "E_CAPTCHA_DETECTION_FAILED"
E_CAPTCHA_STUCK = "E_CAPTCHA_STUCK"

# --- Download ---
E_DOWNLOAD_FAILED = "E_DOWNLOAD_FAILED"
E_DOWNLOAD_TIMEOUT = "E_DOWNLOAD_TIMEOUT"

# --- Catch-all ---
E_UNIMPLEMENTED = "E_UNIMPLEMENTED"
E_UNKNOWN = "E_UNKNOWN"
