[program:autocutsel-clipboard]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/autocutsel -selection CLIPBOARD -pause 100
autostart=%(ENV_AUTOSTART_VNC)s
autorestart=true
priority=910
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/autocutsel.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2
redirect_stderr=true

[program:autocutsel-primary]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/autocutsel -selection PRIMARY -pause 100
autostart=%(ENV_AUTOSTART_VNC)s
autorestart=true
priority=910
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/autocutsel.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2
redirect_stderr=true
