[program:dbus]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
command=/usr/bin/dbus-daemon --session --nofork
    --address=unix:path=%(ENV_AIO_DBUS_SESSION_SOCKET)s
autostart=%(ENV_AUTOSTART_CJK_IME)s
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/dbus.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=2
redirect_stderr=true
