[program:fcitx5]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s",DBUS_SESSION_BUS_ADDRESS="unix:path=%(ENV_AIO_DBUS_SESSION_SOCKET)s",GTK_IM_MODULE="fcitx",QT_IM_MODULE="fcitx",XMODIFIERS="@im=fcitx"
command=/usr/bin/fcitx5 --replace
autostart=%(ENV_AUTOSTART_CJK_IME)s
autorestart=true
priority=905
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/fcitx5.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
redirect_stderr=true
