# default port: 8118 (forward proxy), 18080 (API)
[program:gost]
command=/usr/local/bin/gost -C /opt/gem/gost.yaml
user=%(ENV_USER)s
autorestart=true
priority=899
stdout_logfile=%(ENV_LOG_DIR)s/gost.log
redirect_stderr=true
