[program:mcp-server-browser]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",BROWSER_DOWNLOAD_DIR_EFFECTIVE="%(ENV_BROWSER_DOWNLOAD_DIR_EFFECTIVE)s"
command=/usr/local/bin/mcp-server-browser --port %(ENV_MCP_SERVER_BROWSER_PORT)s --host 127.0.0.1 --browser chrome --output-dir %(ENV_BROWSER_DOWNLOAD_DIR_EFFECTIVE)s --cdp-endpoint http://127.0.0.1:%(ENV_BROWSER_REMOTE_DEBUGGING_PORT)s/json/version --viewport-size "0,0"
autostart=%(ENV_AUTOSTART_MCP_BROWSER)s
autorestart=true
priority=899
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/mcp-server-browser.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
redirect_stderr=true
