[program:python-server]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",JUPYTER_PLATFORM_DIRS="1",XAUTHORITY="/home/%(ENV_USER)s/.Xauthority",DISPLAY="%(ENV_DISPLAY)s",PYTHONWARNINGS="ignore"
command=/opt/gem/supervisord/python_srv_wrapper.sh --host 127.0.0.1 --port %(ENV_SANDBOX_SRV_PORT)s --ws-ping-interval 30 --mcp-config /opt/gem/mcp-hub.json --filter-mcp-servers sandbox --workspace %(ENV_WORKSPACE)s
autorestart=true
stopwaitsecs=60
priority=100
user=%(ENV_USER)s
stdout_logfile=%(ENV_LOG_DIR)s/python-server.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
redirect_stderr=true
