[program:log_tail]
command=/bin/bash -c 'tail -F %(ENV_LOG_DIR)s/python-server.log | while IFS= read -r line; do echo "[SERVER] $line"; done'
priority=999
autostart=%(ENV_LOG_STDOUT_SERVER)s
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

